project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    logo: media/logo.png
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
    background: "#0b1f3a"
    foreground: "white"

  page-footer:
    center: "Â© 2026 Aashik Bhalodia"

format:
  html:
    from: markdown+fenced_divs
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



