project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    right:
      - href: index.qmd
        text: Home
      - publications.qmd
      - blog.qmd

format:
  html:
    from: markdown+fenced_divs
    theme:
      - cosmo
      - brand
    primary: "#0b1f3a"   # navy blue
    css: styles.css
    toc: true



